<?php

/**
 * @file
 * Contains geofield_3111.module.
 */

/**
 * Implements hook_leaflet_map_view_style_alter().
 */
function geofield_311_leaflet_map_view_style_alter(array &$map_settings) {
  $map_settings["map"]['geojson_app_limit'] = \Drupal::service('geofield_311.service')
    ->getGeojsonAppLimit();
}

/**
 * Implements hook_leaflet_default_widget_alter().
 */
function geofield_311_leaflet_default_widget_alter(array &$map_settings) {
  $map_settings['geojson_app_limit'] = \Drupal::service('geofield_311.service')
    ->getGeojsonAppLimit();
}
