<?php

/**
 * @file
 * Contains italo_module.module.
 */

use Drupal\views\Plugin\views\query\Sql;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\node\NodeInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\paragraphs\Entity\Paragraph;

/**
 * Implements hook_page_attachments().
 */
function italo_module_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'italo_module/common';
  $page['#attached']['library'][] = 'italo_module/leaflet_map_interactions';
  $page['#attached']['library'][] = 'italo_module/leaflet_node_forced_bounds';
  $page['#attached']['library'][] = 'italo_module/leaflet-arrowheads';
  $page['#attached']['library'][] = 'italo_module/leaflet_drupal_overrides';
}

/**
 * Implements hook_views_query_alter().
 */
function italo_module_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {

  // Avoiding Paragraphs Duplications in Geoplaces Leaflet View Map.
  // @see https://www.drupal.org/project/paragraphs/issues/2941499
  if ($view->storage->id() == 'geo_places' && $query instanceof Sql) {
    $query->addField('paragraphs_item_field_data_node__field_locations', 'id', '', ['function' => 'groupby']);
    $query->addGroupBy('paragraphs_item_field_data_node__field_locations.id');
  }
}

/**
 * Implements hook_entity_base_field_info().
 *
 * Generate the Geoimage Caption computed field.
 */
function italo_module_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];
  if ($entity_type->id() === 'node') {
    // Add a field that shows a link to the user's current company.
    $fields['geoimage_caption'] = BaseFieldDefinition::create('string')
      ->setName('geoimage_caption')
      ->setLabel(t('Geoimage Caption'))
      ->setComputed(TRUE)
      ->setClass('\Drupal\italo_module\GeoimageCaptionFieldItemList')
      ->setDisplayConfigurable('view', TRUE)
      ->setDisplayOptions('view', [
        'label' => 'hidden',
        'weight' => -5,
      ]);

    // Add a field that defines the Geoimage Storing Folder.
    $fields['geoimage_storing_folder'] = BaseFieldDefinition::create('string')
      ->setName('geoimage_storing_folder')
      ->setLabel(t('Geoimage Storing Folder'))
      ->setComputed(TRUE)
      ->setClass('\Drupal\italo_module\GeoimageStoringFolderFieldItemList')
      ->setDisplayConfigurable('view', FALSE);

    // Add a field that defines the Territorial Report Level, if active.
    $fields['territorial_report_active_level'] = BaseFieldDefinition::create('string')
      ->setName('territorial_report_active_level')
      ->setLabel(t('Territorial Report Active Level'))
      ->setComputed(TRUE)
      ->setClass('\Drupal\italo_module\TerritorialReportActiveLevelFieldItemList')
      ->setDisplayConfigurable('view', TRUE);

  }
  return $fields;
}

/**
 * Implements hook_views_data_alter().
 */
function italo_module_views_data_alter(array &$data) {
  if (isset($data['node'])) {
    // Add the geoimage_storing_folder field to Views.
    $data['node']['geoimage_storing_folder'] = [
      'title' => t('Geoimage Storing Folder'),
      'field' => [
        'id' => 'field',
        'default_formatter' => 'string',
        'field_name' => 'geoimage_storing_folder',
      ],
    ];

    $data['node']['territorial_report_active_level'] = [
      'title' => t('Territorial Report Active Level'),
      'field' => [
        'id' => 'field',
        'default_formatter' => 'string',
        'field_name' => 'territorial_report_active_level',
      ],
    ];
  }
}

/**
 * Implements hook_ENTITY_TYPE_view() for node entities.
 */
function italo_module_node_view(array &$build, NodeInterface $node, EntityViewDisplayInterface $display, $view_mode) {
  if ($view_mode === 'full' && $node->bundle() === 'geoplace') {
    $locations = $node->get('field_locations')->getValue();
    $geofields = [];
    /** @var Drupal\leaflet\LeafletService $leafletService */
    $leafletService = \Drupal::service('leaflet.service');
    foreach ($locations as $location) {
      $paragraph = Paragraph::load($location['target_id']);
      $geofields[] = $paragraph->field_geofield->value;
    }
    $geofields = $leafletService->leafletProcessGeofield($geofields);

    // Add DrupalSettings for forcing bounds on this specific Node.
    $build['#attached']['drupalSettings']['leaflet']['node_forced_bounds'] = [
      'node_id' => $node->id(),
      'currentPath' => 'node/' . $node->id(),
      'geofields' => $geofields,
    ];

  }
}
